<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sTM" nsURI="http://www.example.org/sTM" nsPrefix="sTM">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SnapshotClassifier" eSuperTypes="#//Classifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueIds AcyclicScenario OneScenario SameSnapshot"/>
    </eAnnotations>
    <eOperations name="getNext" eType="#//SnapshotClassifier"/>
    <eOperations name="getPost" ordered="false" upperBound="-1" eType="#//SnapshotClassifier"/>
    <eOperations name="getPrevious" eType="#//SnapshotClassifier"/>
    <eOperations name="getPre" ordered="false" upperBound="-1" eType="#//SnapshotClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="snapshotObjects" upperBound="-1"
        eType="#//SnapshotComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextT" eType="#//TransitionClass"
        eOpposite="#//TransitionClass/beforeS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beforeT" eType="#//TransitionClass"
        eOpposite="#//TransitionClass/nextS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFirst" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLast" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionClass" eSuperTypes="#//NamedElement #//Classifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SameTrans"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isParentClass" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionParent" lowerBound="1"
        eType="#//TransitionClass" eOpposite="#//TransitionClass/transitionSubClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionSubClasses" upperBound="-1"
        eType="#//TransitionClass" eOpposite="#//TransitionClass/transitionParent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beforeS" lowerBound="1"
        eType="#//SnapshotClassifier" eOpposite="#//SnapshotClassifier/nextT"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextS" lowerBound="1" eType="#//SnapshotClassifier"
        eOpposite="#//SnapshotClassifier/beforeT"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postObjects" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnapshotComponent" eSuperTypes="#//Classifier">
    <eOperations name="getNext" eType="#//SnapshotComponent"/>
    <eOperations name="getPost" ordered="false" upperBound="-1" eType="#//SnapshotComponent"/>
    <eOperations name="getPrevious" eType="#//SnapshotComponent"/>
    <eOperations name="getPre" ordered="false" upperBound="-1" eType="#//SnapshotComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryOperations" upperBound="-1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//TypedElement #//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEnd" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberEnd" lowerBound="2"
        upperBound="-1" eType="#//Property" eOpposite="#//Property/association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
        eType="#//ValueSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//NamedElement #//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" eType="#//Association"
        eOpposite="#//Association/memberEnd"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedProperty" upperBound="-1"
        eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="#//AggregationKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedElement" upperBound="-1"
        eType="#//TypedElement" eOpposite="#//TypedElement/type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" upperBound="-1"
        eType="#//Type" eOpposite="#//Type/typedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiteral" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerationLiteral" upperBound="-1"
        eType="#//EnumerationLiteral" eOpposite="#//EnumerationLiteral/enumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" lowerBound="1"
        eType="#//Enumeration" eOpposite="#//Enumeration/enumerationLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyCondition" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postcondition" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" upperBound="-1"
        eType="#//Generalization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueExpression" eSuperTypes="#//ValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/ocl/2015/Pivot#T-pivot-String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true"
      eSuperTypes="#//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralSpecification" abstract="true"
      eSuperTypes="#//ValueSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralInteger" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/ocl/2015/Pivot#T-pivot-Integer"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralUnlimitedNatural" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/ocl/2015/Pivot#T-pivot-UnlimitedNatural"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralReal" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/ocl/2015/Pivot#T-pivot-Real"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralString" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralNull" eSuperTypes="#//LiteralSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralBoolean">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnapshotAssocClass" eSuperTypes="#//Association #//SnapshotComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" upperBound="-1"
        eType="#//NamedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AggregationKind">
    <eLiterals name="none"/>
    <eLiterals name="shared"/>
    <eLiterals name="composite"/>
  </eClassifiers>
</ecore:EPackage>